model = "gpt-5.2-codex"

[features]
web_search_request = true
skills = true

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp@latest"]

[mcp_servers.git]
command = "uvx"
args = ["mcp-server-git"]
